[project]
name = "usrse26-notebook"
version = "0.2.0"
description = "Notebook submitted to USRSE 2026 (https://us-rse.org/usrse26/) detailing how a CryoCloud onboarding showcasing effective techniques for introducing scientists to large-scale open-access data and cloud-computing workflows. See README.md for further information."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "cmap>=0.7.2",
    "earthaccess>=0.17.0",
    "geopandas>=1.1.4",
    "icesat2-toolkit>=1.3.1",
    "ipykernel>=7.3.0",
    "ipympl>=0.10.0",
    "matplotlib>=3.11.1",
    "pyastronomy>=0.25.0",
    "pytmd>=3.0.9",
    "rasterio>=1.4.4",
    "s3fs>=2026.7.0",
    "xarray[complete]>=2026.7.0",
]
