[project]
name = "usrse26-notebook"
version = "0.2.0"
description = "Notebook submitted to USRSE 2026 (https://us-rse.org/usrse26/) detailing how a CryoCloud onboarding showcasing effective techniques for introducing scientists to large-scale open-access data and cloud-computing workflows. See README.md for further information."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "xarray[complete]>=2026.7.0",
]
